package com.certus.dbmodel;
// Generated Jan 24, 2016 12:46:38 PM by Hibernate Tools 4.3.1


/**
 * Administor generated by hbm2java
 */
public class Administor implements java.io.Serializable {

    private Integer id;
    private String FName;
    private String LName;
    private String email;
    private String password;
    private String image;
    private String userName;
    
    public Administor() {
    }

    public Administor(String FName, String LName, String email, String password, String userName) {
        this.FName = FName;
        this.LName = LName;
        this.email = email;
        this.password = password;
        this.userName = userName;
    }

    public Administor(Integer id, String FName, String LName, String email, String password, String image, String userName) {
        this.id = id;
        this.FName = FName;
        this.LName = LName;
        this.email = email;
        this.password = password;
        this.image = image;
        this.userName = userName;
       
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getFName() {
        return this.FName;
    }

    public void setFName(String FName) {
        this.FName = FName;
    }

    public String getLName() {
        return this.LName;
    }

    public void setLName(String LName) {
        this.LName = LName;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getImage() {
        return this.image;
    }

    public void setImage(String image) {
        this.image = image;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }


}
