package com.certus.dbmodel;
// Generated Jan 24, 2016 12:46:38 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Coupon generated by hbm2java
 */
public class Coupon  implements java.io.Serializable {


     private Integer id;
     private String description;
     private String couponCode;
     private double discount;
     private Date dateAdded;
     private Date dateEnded;
     private boolean availability;
     private Set<Order> orders = new HashSet<>();

    public Coupon() {
    }

	
    public Coupon(String description, String couponCode, double discount, Date dateAdded, Date dateEnded, boolean availability) {
        this.description = description;
        this.couponCode = couponCode;
        this.discount = discount;
        this.dateAdded = dateAdded;
        this.dateEnded = dateEnded;
        this.availability = availability;
    }
    public Coupon(String description, String couponCode, double discount, Date dateAdded, Date dateEnded, boolean availability, Set<Order> orders) {
       this.description = description;
       this.couponCode = couponCode;
       this.discount = discount;
       this.dateAdded = dateAdded;
       this.dateEnded = dateEnded;
       this.availability = availability;
       this.orders = orders;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getCouponCode() {
        return this.couponCode;
    }
    
    public void setCouponCode(String couponCode) {
        this.couponCode = couponCode;
    }
    public double getDiscount() {
        return this.discount;
    }
    
    public void setDiscount(double discount) {
        this.discount = discount;
    }
    public Date getDateAdded() {
        return this.dateAdded;
    }
    
    public void setDateAdded(Date dateAdded) {
        this.dateAdded = dateAdded;
    }
    public Date getDateEnded() {
        return this.dateEnded;
    }
    
    public void setDateEnded(Date dateEnded) {
        this.dateEnded = dateEnded;
    }
    public boolean isAvailability() {
        return this.availability;
    }
    
    public void setAvailability(boolean availability) {
        this.availability = availability;
    }
    public Set<Order> getOrders() {
        return this.orders;
    }
    
    public void setOrders(Set<Order> orders) {
        this.orders = orders;
    }




}


