package com.certus.dbmodel;
// Generated Jan 24, 2016 12:46:38 PM by Hibernate Tools 4.3.1



/**
 * Currency generated by hbm2java
 */
public class Currency  implements java.io.Serializable {


     private Integer id;
     private String currency;
     private String curCode;
     private boolean front;
     private boolean back;
     private double unit;

    public Currency() {
    }

    public Currency(String currency, String curCode, boolean front, boolean back, double unit) {
       this.currency = currency;
       this.curCode = curCode;
       this.front = front;
       this.back = back;
       this.unit = unit;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getCurrency() {
        return this.currency;
    }
    
    public void setCurrency(String currency) {
        this.currency = currency;
    }
    public String getCurCode() {
        return this.curCode;
    }
    
    public void setCurCode(String curCode) {
        this.curCode = curCode;
    }
    public boolean isFront() {
        return this.front;
    }
    
    public void setFront(boolean front) {
        this.front = front;
    }
    public boolean isBack() {
        return this.back;
    }
    
    public void setBack(boolean back) {
        this.back = back;
    }
    public double getUnit() {
        return this.unit;
    }
    
    public void setUnit(double unit) {
        this.unit = unit;
    }




}


