package com.certus.dbmodel;
// Generated Jan 24, 2016 12:46:38 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Expences generated by hbm2java
 */
public class Expences  implements java.io.Serializable {


     private Integer id;
     private ProductHasSize productHasSize;
     private Date date;
     private int qnty;
     private int total;
     private int StockqntyBfUpdate;
    public Expences() {
    }

    public Expences(ProductHasSize productHasSize, Date date, int qnty, int total) {
       this.productHasSize = productHasSize;
       this.date = date;
       this.qnty = qnty;
       this.total = total;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public ProductHasSize getProductHasSize() {
        return this.productHasSize;
    }
    
    public void setProductHasSize(ProductHasSize productHasSize) {
        this.productHasSize = productHasSize;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public int getQnty() {
        return this.qnty;
    }
    
    public void setQnty(int qnty) {
        this.qnty = qnty;
    }
    public int getTotal() {
        return this.total;
    }
    
    public void setTotal(int total) {
        this.total = total;
    }

    public int getStockqntyBfUpdate() {
        return StockqntyBfUpdate;
    }

    public void setStockqntyBfUpdate(int StockqntyBfUpdate) {
        this.StockqntyBfUpdate = StockqntyBfUpdate;
    }




}


