package com.certus.dbmodel;
// Generated Jan 24, 2016 12:46:38 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Order generated by hbm2java
 */
public class Order implements java.io.Serializable {

    private Integer id;
    private Coupon coupon;
    private User user;
    private Date dateOrdered;
    private String orderAddress;
    private String status;
    private String productIds;
    private String quantities;
    private String sizes;
    private String name;
    private String email;
    private String tel;
    private String city;
    private String payment_method;
    private String invoNum;
    private double grandTot;
    private Set<Sales> sales = new HashSet<>();
    private Set<Messages> messages = new HashSet<>();

    public Order() {
    }

    public Order(Integer id, Coupon coupon, User user, Date dateOrdered, String orderAddress, String status) {
        this.id = id;
        this.coupon = coupon;
        this.user = user;
        this.dateOrdered = dateOrdered;
        this.orderAddress = orderAddress;
        this.status = status;

    }

    public Order(Integer id, Coupon coupon, User user, Date dateOrdered, String orderAddress, String status, String productIds, String quantities, String sizes, String name, String email, String tel, String city, String payment_method) {
        this.id = id;
        this.coupon = coupon;
        this.user = user;
        this.dateOrdered = dateOrdered;
        this.orderAddress = orderAddress;
        this.status = status;
        this.productIds = productIds;
        this.quantities = quantities;
        this.sizes = sizes;
        this.name = name;
        this.email = email;
        this.tel = tel;
        this.city = city;
        this.payment_method = payment_method;
    }

    public Order(Integer id, Coupon coupon, User user, Date dateOrdered, String orderAddress, String status, String productIds, String quantities, String sizes, String name, String email, String tel, String city, String payment_method, String invoNum, Set<Sales> sales, Set<Messages> messages) {
        this.id = id;
        this.coupon = coupon;
        this.user = user;
        this.dateOrdered = dateOrdered;
        this.orderAddress = orderAddress;
        this.status = status;
        this.productIds = productIds;
        this.quantities = quantities;
        this.sizes = sizes;
        this.name = name;
        this.email = email;
        this.tel = tel;
        this.city = city;
        this.payment_method = payment_method;
        this.invoNum = invoNum;
        this.sales = sales;
        this.messages = messages;
    }

    public Order(Date dateOrdered, double grandTotal, String orderAddress, String status) {

        this.dateOrdered = dateOrdered;
        this.orderAddress = orderAddress;
        this.status = status;
    }

    public Order(Coupon coupon, User user, Date dateOrdered, String orderAddress, String status) {
        this.coupon = coupon;
        this.user = user;
        this.dateOrdered = dateOrdered;
        this.orderAddress = orderAddress;
        this.status = status;

    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Coupon getCoupon() {
        return this.coupon;
    }

    public void setCoupon(Coupon coupon) {
        this.coupon = coupon;
    }

    public User getUser() {
        return this.user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public Date getDateOrdered() {
        return this.dateOrdered;
    }

    public void setDateOrdered(Date dateOrdered) {
        this.dateOrdered = dateOrdered;
    }

    public String getOrderAddress() {
        return this.orderAddress;
    }

    public void setOrderAddress(String orderAddress) {
        this.orderAddress = orderAddress;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getProductIds() {
        return productIds;
    }

    public void setProductIds(String productIds) {
        this.productIds = productIds;
    }

    public String getQuantities() {
        return quantities;
    }

    public void setQuantities(String quantities) {
        this.quantities = quantities;
    }

    public String getSizes() {
        return sizes;
    }

    public void setSizes(String sizes) {
        this.sizes = sizes;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getTel() {
        return tel;
    }

    public void setTel(String tel) {
        this.tel = tel;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getPayment_method() {
        return payment_method;
    }

    public void setPayment_method(String payment_method) {
        this.payment_method = payment_method;
    }

    public Set<Sales> getSales() {
        return sales;
    }

    public void setSales(Set<Sales> sales) {
        this.sales = sales;
    }

    public String getInvoNum() {
        return invoNum;
    }

    public void setInvoNum(String invoNum) {
        this.invoNum = invoNum;
    }

    public double getGrandTot() {
        return grandTot;
    }

    public void setGrandTot(double grandTot) {
        this.grandTot = grandTot;
    }

    public Set<Messages> getMessages() {
        return messages;
    }

    public void setMessages(Set<Messages> messages) {
        this.messages = messages;
    }

}
