package com.certus.dbmodel;
// Generated Jan 24, 2016 12:46:38 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * ProductHasSize generated by hbm2java
 */
public class ProductHasSize implements java.io.Serializable {

    private Integer id;
    private Product product;
    private Size size;
    private int qnty;
    private double price;
    private Set<Expences> expenceses = new HashSet<>();

    public ProductHasSize() {
    }

    public ProductHasSize(Product product, Size size, int qnty, double price) {
        this.product = product;
        this.size = size;
        this.qnty = qnty;
        this.price = price;
    }

    public ProductHasSize(Product product, Size size, int qnty, double price, Set<Expences> expenceses) {
        this.product = product;
        this.size = size;
        this.qnty = qnty;
        this.price = price;
        this.expenceses = expenceses;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Product getProduct() {
        return this.product;
    }

    public void setProduct(Product product) {
        this.product = product;
    }

    public Size getSize() {
        return this.size;
    }

    public void setSize(Size size) {
        this.size = size;
    }

    public int getQnty() {
        return this.qnty;
    }

    public void setQnty(int qnty) {
        this.qnty = qnty;
    }

    public double getPrice() {
        return this.price;
    }

    public void setPrice(double price) {
        this.price = price;
    }

    public Set<Expences> getExpenceses() {
        return this.expenceses;
    }

    public void setExpenceses(Set<Expences> expenceses) {
        this.expenceses = expenceses;
    }

    public double getDiscountPrice(double price, int percentage) {
        return (int) (price - (price * (percentage / 100.0f)));
    }

    public String getSize(Set<ProductHasSize> phs, int pid) {
        return phs.stream().filter(p -> p.getProduct().getId() == pid)
                .findFirst().get().getSize().getSizeName();
    }

}
