package com.certus.dbmodel;
// Generated Jan 24, 2016 12:46:38 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Product generated by hbm2java
 */
public class Product implements java.io.Serializable {

    private Integer id;
    private Brand brand;
    private SubCategory subCategory;
    private String name;
    private String imageMain;
    private int discountPrice;
    private String description;
    private boolean availability;
    private String specs;
    private String featuredItems;
    private Set<ProImg> proImgs = new HashSet<>();
    private Set<Rate> rates = new HashSet<>();
    private Set<WishList> wishLists = new HashSet<>();
    private Set<Review> reviews = new HashSet<>();
    private Set<Order> orders = new HashSet<>();
    private Set<ProductHasSize> productHasSizes = new HashSet<>();
    private Set<SliderFacts> sliderFacts = new HashSet<>();

    public Product() {
    }

    public Product(Brand brand, SubCategory subCategory, String name, int discountPrice, boolean availability) {
        this.brand = brand;
        this.subCategory = subCategory;
        this.name = name;
        this.discountPrice = discountPrice;
        this.availability = availability;
    }

    public Product(Brand brand, SubCategory subCategory, String name, String imageMain, int discountPrice, String description, boolean availability, String specs, String featuredItems, Set<ProImg> proImgs, Set<Rate> rates, Set<WishList> wishLists, Set<Review> reviews, Set<Order> orders, Set<ProductHasSize> productHasSizes, Set<SliderFacts> sliderFacts
    ) {
        this.brand = brand;
        this.subCategory = subCategory;
        this.name = name;
        this.imageMain = imageMain;
        this.discountPrice = discountPrice;
        this.description = description;
        this.availability = availability;
        this.specs = specs;
        this.featuredItems = featuredItems;
        this.proImgs = proImgs;
        this.rates = rates;
        this.wishLists = wishLists;
        this.reviews = reviews;
        this.orders = orders;
        this.productHasSizes = productHasSizes;
        this.sliderFacts = sliderFacts;

    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Brand getBrand() {
        return this.brand;
    }

    public void setBrand(Brand brand) {
        this.brand = brand;
    }

    public SubCategory getSubCategory() {
        return this.subCategory;
    }

    public void setSubCategory(SubCategory subCategory) {
        this.subCategory = subCategory;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getImageMain() {
        return this.imageMain;
    }

    public void setImageMain(String imageMain) {
        this.imageMain = imageMain;
    }

    public int getDiscountPrice() {
        return this.discountPrice;
    }

    public void setDiscountPrice(int discountPrice) {
        this.discountPrice = discountPrice;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public boolean isAvailability() {
        return this.availability;
    }

    public void setAvailability(boolean availability) {
        this.availability = availability;
    }

    public String getSpecs() {
        return this.specs;
    }

    public void setSpecs(String specs) {
        this.specs = specs;
    }

    public String getFeaturedItems() {
        return this.featuredItems;
    }

    public void setFeaturedItems(String featuredItems) {
        this.featuredItems = featuredItems;
    }

    public Set<ProImg> getProImgs() {
        return this.proImgs;
    }

    public void setProImgs(Set<ProImg> proImgs) {
        this.proImgs = proImgs;
    }

    public Set<Rate> getRates() {
        return this.rates;
    }

    public void setRates(Set<Rate> rates) {
        this.rates = rates;
    }

    public Set<WishList> getWishLists() {
        return this.wishLists;
    }

    public void setWishLists(Set<WishList> wishLists) {
        this.wishLists = wishLists;
    }

    public Set<Review> getReviews() {
        return this.reviews;
    }

    public void setReviews(Set<Review> reviews) {
        this.reviews = reviews;
    }

    public Set<Order> getOrders() {
        return this.orders;
    }

    public void setOrders(Set<Order> orders) {
        this.orders = orders;
    }

    public Set<ProductHasSize> getProductHasSizes() {
        return this.productHasSizes;
    }

    public void setProductHasSizes(Set<ProductHasSize> productHasSizes) {
        this.productHasSizes = productHasSizes;
    }

    public double getDiscountPrice(double price, int percentage) {
        return (int) (price - (price * (percentage / 100.0f)));
    }

    public Set<SliderFacts> getSliderFacts() {
        return sliderFacts;
    }

    public void setSliderFacts(Set<SliderFacts> sliderFacts) {
        this.sliderFacts = sliderFacts;
    }

}
