package com.certus.dbmodel;
// Generated Jan 24, 2016 12:46:38 PM by Hibernate Tools 4.3.1



/**
 * ProImg generated by hbm2java
 */
public class ProImg  implements java.io.Serializable {


     private Integer id;
     private Product product;
     private String image;

    public ProImg() {
    }

	
    public ProImg(Product product) {
        this.product = product;
    }
    public ProImg(Product product, String image) {
       this.product = product;
       this.image = image;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }




}


