package com.certus.dbmodel;
// Generated Jan 24, 2016 12:46:38 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Promotions generated by hbm2java
 */
public class Promotions  implements java.io.Serializable {


     private Integer id;
     private Product proId;
     private Date dateAdded;
     private Date dateEnded;
     private boolean status;
     private String description;
     private String color;

    public Promotions() {
    }

    

    public Promotions(Integer id, Product proId, Date dateAdded, Date dateEnded, boolean status, String description, String color) {
        this.id = id;
        this.proId = proId;
        this.dateAdded = dateAdded;
        this.dateEnded = dateEnded;
        this.status = status;
        this.description = description;
        this.color = color;
    }
    
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public Product getProId() {
        return proId;
    }

    public void setProId(Product proId) {
        this.proId = proId;
    }
    
    public Date getDateAdded() {
        return this.dateAdded;
    }
    
    public void setDateAdded(Date dateAdded) {
        this.dateAdded = dateAdded;
    }
    public Date getDateEnded() {
        return this.dateEnded;
    }
    
    public void setDateEnded(Date dateEnded) {
        this.dateEnded = dateEnded;
    }
    public boolean isStatus() {
        return this.status;
    }
    
    public void setStatus(boolean status) {
        this.status = status;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getColor() {
        return color;
    }

    public void setColor(String color) {
        this.color = color;
    }




}


