package com.certus.dbmodel;
// Generated Jan 24, 2016 12:46:38 PM by Hibernate Tools 4.3.1



/**
 * Rate generated by hbm2java
 */
public class Rate  implements java.io.Serializable {


     private Integer id;
     private Product product;
     private User user;
     private double rate;

    public Rate() {
    }

    public Rate(Product product, User user, double rate) {
       this.product = product;
       this.user = user;
       this.rate = rate;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public double getRate() {
        return this.rate;
    }
    
    public void setRate(double rate) {
        this.rate = rate;
    }




}


