package com.certus.dbmodel;
// Generated Jan 24, 2016 12:46:38 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Review generated by hbm2java
 */
public class Review  implements java.io.Serializable {


     private Integer id;
     private Product product;
     private User user;
     private String comment;
     private Date dateComnt;
     private boolean availability;

    public Review() {
    }

    public Review(Product product, User user, String comment, Date dateComnt, boolean availability) {
       this.product = product;
       this.user = user;
       this.comment = comment;
       this.dateComnt = dateComnt;
       this.availability = availability;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }
    public Date getDateComnt() {
        return this.dateComnt;
    }
    
    public void setDateComnt(Date dateComnt) {
        this.dateComnt = dateComnt;
    }
    public boolean isAvailability() {
        return this.availability;
    }
    
    public void setAvailability(boolean availability) {
        this.availability = availability;
    }




}


