package com.certus.dbmodel;
// Generated Jan 24, 2016 12:46:38 PM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Sales generated by hbm2java
 */
public class Sales implements java.io.Serializable {

    private Integer id;
    private Date dateDone;
    private Double grandTotal;
    private Order order;
    private String status;
    private String description;

    public Sales() {
    }

    public Sales(Date dateDone) {
        this.dateDone = dateDone;
    }

    public Sales(Integer id, Date dateDone, Double grandTotal, Order order, String status, String description) {
        this.id = id;
        this.dateDone = dateDone;
        this.grandTotal = grandTotal;
        this.order = order;
        this.status = status;
        this.description = description;
    }

    public Double getGrandTotal() {
        return grandTotal;
    }

    public void setGrandTotal(Double grandTotal) {
        this.grandTotal = grandTotal;
    }

    public Order getOrder() {
        return order;
    }

    public void setOrder(Order order) {
        this.order = order;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Date getDateDone() {
        return this.dateDone;
    }

    public void setDateDone(Date dateDone) {
        this.dateDone = dateDone;
    }

}
