package com.certus.dbmodel;
// Generated Jan 24, 2016 12:46:38 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Size generated by hbm2java
 */
public class Size  implements java.io.Serializable {


     private Integer id;
     private String sizeName;
     private boolean availability;
     private Set<ProductHasSize> productHasSizes = new HashSet<>();

    public Size() {
    }

	
    public Size(String sizeName, boolean availability) {
        this.sizeName = sizeName;
        this.availability = availability;
    }
    public Size(String sizeName, boolean availability, Set<ProductHasSize> productHasSizes) {
       this.sizeName = sizeName;
       this.availability = availability;
       this.productHasSizes = productHasSizes;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getSizeName() {
        return this.sizeName;
    }
    
    public void setSizeName(String sizeName) {
        this.sizeName = sizeName;
    }
    public boolean isAvailability() {
        return this.availability;
    }
    
    public void setAvailability(boolean availability) {
        this.availability = availability;
    }
    public Set<ProductHasSize> getProductHasSizes() {
        return this.productHasSizes;
    }
    
    public void setProductHasSizes(Set<ProductHasSize> productHasSizes) {
        this.productHasSizes = productHasSizes;
    }




}


