package com.certus.dbmodel;
// Generated Jan 24, 2016 12:46:38 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * SubCategory generated by hbm2java
 */
public class SubCategory  implements java.io.Serializable {


     private Integer id;
     private Category category;
     private String subCategoryName;
     private boolean availability;
     private Set<Product> products = new HashSet<>();

    public SubCategory() {
    }

	
    public SubCategory(Category category, String subCategoryName, boolean availability) {
        this.category = category;
        this.subCategoryName = subCategoryName;
        this.availability = availability;
    }
    public SubCategory(Category category, String subCategoryName, boolean availability, Set<Product> products) {
       this.category = category;
       this.subCategoryName = subCategoryName;
       this.availability = availability;
       this.products = products;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Category getCategory() {
        return this.category;
    }
    
    public void setCategory(Category category) {
        this.category = category;
    }
    public String getSubCategoryName() {
        return this.subCategoryName;
    }
    
    public void setSubCategoryName(String subCategoryName) {
        this.subCategoryName = subCategoryName;
    }
    public boolean isAvailability() {
        return this.availability;
    }
    
    public void setAvailability(boolean availability) {
        this.availability = availability;
    }
    public Set<Product> getProducts() {
        return this.products;
    }
    
    public void setProducts(Set<Product> products) {
        this.products = products;
    }




}


