package com.certus.dbmodel;
// Generated Jan 24, 2016 12:46:38 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * WishList generated by hbm2java
 */
public class WishList  implements java.io.Serializable {


     private Integer id;
     private Product product;
     private User user;
     private Date dateAdded;

    public WishList() {
    }

    public WishList(Product product, User user, Date dateAdded) {
       this.product = product;
       this.user = user;
       this.dateAdded = dateAdded;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Date getDateAdded() {
        return this.dateAdded;
    }
    
    public void setDateAdded(Date dateAdded) {
        this.dateAdded = dateAdded;
    }




}


